### ISSUE TITLE
"Checkout this games discussion" should be "Check out this game's discussion"

### ISSUE THREAD

**Issue by theolaa** [StatsForSteam/StatsForSteam#28]
I would've made a PR myself, but I'm not 100% on if the `'` would mess things up so I'll leave that to you guys.

**Comment by theolaa** [comment]
Oh, it's in [Dashboard.js](https://github.com/StatsForSteam/StatsForSteam/blob/main/client/src/components/Dashboard.js)

**Comment by AndrewWMeier** [comment]
good catch @theolaa will make sure to fix this at some point

**Comment by brezden** [comment]
> Oh, it's in [Dashboard.js](https://github.com/StatsForSteam/StatsForSteam/blob/main/client/src/components/Dashboard.js)

Thank you for the typo Theo. Just added it in the latest commit!
